#!/bin/bash

cd /raspicopter;

# Update Git
git reset --hard;
git pull;

# Instaling npm
npm install;

# Install services
cp init.d/raspicopter /etc/init.d/raspicopter;
chmod ugo+x /etc/init.d/raspicopter;
update-rc.d raspicopter enable;
update-rc.d raspicopter start;

echo "Updated!!";
exit 0;