#!/bin/bash

service raspicopter stop;

cd /raspicopter;

# Update Git
git reset --hard;
git pull;

# Instaling npm
[ ! -d "node_modules" ] && npm install;

# Install services
mkdir -p /usr/local/var/run;
cp init.d/raspicopter /etc/init.d/raspicopter;
chmod ugo+x /etc/init.d/raspicopter;
update-rc.d raspicopter enable;
update-rc.d raspicopter start;

echo "Updated!!";
service raspicopter start;
exit 0;